name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "5 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRIC_TOKEN }}

          # Options
          user: DevPeter05
          template: classic
          base: header, activity, community, repositories
          base_hireable: true
          config_timezone: Europe/London
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 360
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 90
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_notable: yes
          plugin_notable_filter: stars:>1
          plugin_notable_repositories: yes
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 360
          plugin_habits_facts: yes
          plugin_skyline: true
          plugin_skyline_frames: 120
          plugin_fortune: true
          
